name: flutter_map_marker_popup
description: A plugin for flutter_map to show a customisable popup Widget when a marker is tapped. Also provides methods to show/hide popups.
version: 1.0.0+2
homepage: https://github.com/rorystephenson/flutter_map_marker_popup

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_map:
    git:
      url: https://github.com/xni06/flutter_map.git
      ref: feature/add-marker-data-property

  animated_stack_widget: ^0.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3
